### ISSUE TITLE
Error when running in a project with extra locale

### ISSUE THREAD

**Issue by masimplo** [Jamaks/ng-app-counter#1]
Having installed ng-app-counter v0.0.2 globally, I get this error:
```
Parsing...
Failed to read JSON file /Users/masimplo/Repos/projectX/node_modules/@angular/common/locales/pl.metadata.json
/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:76
            throw e;
            ^

TypeError: Cannot read property 'version' of null
    at readMetadataFile (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:68:33)
    at Object.readMetadata (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:37:29)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:469:38)
    at StaticSymbolResolver.getModuleMetadata (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/@angular/compiler/bundles/compiler.umd.js:22867:49)
    at StaticSymbolResolver.hasDecorators (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/@angular/compiler/bundles/compiler.umd.js:22625:33)
    at /Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/ngast/ngast.bundle.js:2597:70
    at Array.filter (<anonymous>)
    at ProjectSymbols.extractProgramSymbols (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/ngast/ngast.bundle.js:2597:14)
    at ProjectSymbols.getPipes (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/node_modules/ngast/ngast.bundle.js:2535:21)
    at Object.ngcounter (/Users/masimplo/.nvm/versions/node/v8.12.0/lib/node_modules/ng-app-counter/counter.js:34:37)
```

The line that triggers it is:
```ts
import { registerLocaleData } from '@angular/common';
import localePl from '@angular/common/locales/pl';

registerLocaleData(localePl, 'pl');
```

**Comment by irustm** [comment]
please try use ng-app-counter@0.5.0
