### ISSUE TITLE
Error: Multiple root routing modules

### ISSUE THREAD

**Issue by splincode** [Jamaks/ng-app-counter#18]
Repro: clone repo `https://github.com/angular-ru/angular-ru-sdk/` and run

```ts
$  npx ng-app-counter -p ./tsconfig.json 
npx: installed 125 in 23.993s

Parse modules...

Modules: 104 
Pipes: 43 
Directives: 39 
Components: 102 
Injectables: 241 
Classes: 591 

Parse routes...

Error: Multiple root routing modules found /Users/m.ivanov4/Downloads/Develop/Github/Angular-RU/angular-ru-sdk/packages/cdk/integration/apps/cdk/src/app.module.ts, /Users/m.ivanov4/Downloads/Develop/Github/Angular-RU/angular-ru-sdk/packages/cdk/integration/apps/flex-layout/src/app-routing.module.ts, /Users/m.ivanov4/Downloads/Develop/Github/Angular-RU/angular-ru-sdk/packages/cdk/integration/apps/http/src/app-routing.module.ts, /Users/m.ivanov4/Downloads/Develop/Github/Angular-RU/angular-ru-sdk/packages/cdk/integration/apps/tooltip/src/app-routing.module.ts, /Users/m.ivanov4/Downloads/Develop/Github/Angular-RU/angular-ru-sdk/packages/cdk/integration/apps/virtual-table/src/app-routing.module.ts, /Users/m.ivanov4/Downloads/Develop/Github/Angular-RU/angular-ru-sdk/packages/ngxs/integration/app/src/app-routing.module.ts
    at Object.exports.findRootModule (/Users/m.ivanov4/.npm/_npx/2699/lib/node_modules/ng-app-counter/node_modules/guess-parser/dist/guess-parser/index.js:194:15)
    at Object.exports.parseRoutes [as parseAngularRoutes] (/Users/m.ivanov4/.npm/_npx/2699/lib/node_modules/ng-app-counter/node_modules/guess-parser/dist/guess-parser/index.js:958:51)
    at Object.ngcounter (/Users/m.ivanov4/.npm/_npx/2699/lib/node_modules/ng-app-counter/counter.js:28:42)
    at Object.<anonymous> (/Users/m.ivanov4/.npm/_npx/2699/lib/node_modules/ng-app-counter/bin/ng-app-counter:5:48)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at /Users/m.ivanov4/.config/yarn/global/node_modules/npm/node_modules/libnpx/index.js:268:14

{"allModules":104,"allPipes":43,"allDirectives":39,"allComponents":102,"allInjectables":241,"classes":591,"allRoutes":0,"lazyRoutes":0}
```

**Comment by irustm** [comment]
Thanks for this issue. 

Fixed in the next release, 0.6.2

Now ng-app-counter supports not only one root module

<img width="314" alt="parser" src="https://user-images.githubusercontent.com/16316579/137595668-17691cfc-62e7-4a40-86cd-fde2d65d8bc6.png">
